// Generates src/width-data.ts from the Unicode Character Database. Run with any TS runner, e.g.
//   pnpm dlx tsx scripts/gen-width.ts
// The Unicode version is pinned for reproducibility — bump VERSION and re-run on a Unicode update.
//
// Display width is derived from authoritative properties, the way wcwidth / unicode-width do it:
//   - WIDE (2 cols): East Asian Width W or F, plus default-emoji-presentation glyphs.
//   - ZERO (0 cols): combining marks (Mn, Me), format chars (Cf), Hangul Jamo medial/final.
//   - everything else: 1 col (East Asian "Ambiguous" stays narrow — the terminal convention).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const VERSION = "16.0.0";
const BASE = `https://www.unicode.org/Public/${VERSION}/ucd`;

type Range = [number, number];

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url} → ${res.status}`);
  return res.text();
}

// Pull every "XXXX" / "XXXX..YYYY ; Prop" row whose property passes `wanted` out of a UCD file.
function parseRanges(text: string, wanted: (prop: string) => boolean): Range[] {
  const ranges: Range[] = [];
  for (const raw of text.split("\n")) {
    const line = (raw.includes("#") ? raw.slice(0, raw.indexOf("#")) : raw).trim();
    if (!line) continue;
    const [codes, prop] = line.split(";").map((s) => s.trim());
    if (!prop || !wanted(prop)) continue;
    const m = /^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?$/.exec(codes);
    if (!m) continue;
    const lo = parseInt(m[1], 16);
    ranges.push([lo, m[2] ? parseInt(m[2], 16) : lo]);
  }
  return ranges;
}

// Sort + merge touching/overlapping ranges so the runtime table is minimal.
function coalesce(ranges: Range[]): Range[] {
  ranges.sort((a, b) => a[0] - b[0]);
  const out: Range[] = [];
  for (const [lo, hi] of ranges) {
    const last = out.at(-1);
    if (last && lo <= last[1] + 1) last[1] = Math.max(last[1], hi);
    else out.push([lo, hi]);
  }
  return out;
}

function emit(ranges: Range[]): string {
  const nums = ranges.flat();
  let body = "";
  for (let i = 0; i < nums.length; i++) body += (i % 16 === 0 ? "\n  " : "") + nums[i] + ", ";
  return `[${body}\n]`;
}

const [eaw, emoji, gc] = await Promise.all([
  fetchText(`${BASE}/EastAsianWidth.txt`),
  fetchText(`${BASE}/emoji/emoji-data.txt`),
  fetchText(`${BASE}/extracted/DerivedGeneralCategory.txt`),
]);

const wide = coalesce([
  ...parseRanges(eaw, (p) => p === "W" || p === "F"),
  ...parseRanges(emoji, (p) => p === "Emoji_Presentation"),
]);
const zero = coalesce([
  ...parseRanges(gc, (p) => p === "Mn" || p === "Me" || p === "Cf"),
  [0x1160, 0x11ff], // Hangul Jamo medial/final — combine onto the leading jamo, zero display width
]);

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "width-data.ts");
writeFileSync(
  out,
  `// GENERATED by scripts/gen-width.ts from the Unicode Character Database ${VERSION} — do not edit.\n` +
    `// Flat, sorted, inclusive [start, end, …] code-point ranges; binary-searched by width.ts.\n\n` +
    `export const UNICODE_VERSION = "${VERSION}";\n\n` +
    `/** East Asian Wide/Fullwidth + default-emoji-presentation → 2 columns. */\n` +
    `export const WIDE: readonly number[] = ${emit(wide)};\n\n` +
    `/** Combining marks, format chars, Hangul Jamo medial/final → 0 columns. */\n` +
    `export const ZERO: readonly number[] = ${emit(zero)};\n`,
);
console.log(`wrote ${out}\n  WIDE: ${wide.length} ranges  ZERO: ${zero.length} ranges`);
